name: dummy-stack
services:
  dummy:
    image: alpine:latest
    container_name: dummy-secret-test
    restart: unless-stopped
    environment:
      password: ${password}
    volumes:
      - ./dummy-dir:/opt/dummy
    command:
      - sh
      - -c
      - |
        echo "Container started"
        echo "Secret contents:"
        cat /run/secrets/test_secret
        sleep infinity
    

